#!/bin/bash

# ------------------------------------------------------------------------------
# Charger la conf du module
# ------------------------------------------------------------------------------
REPCOURANT=$(cd $(dirname ${BASH_SOURCE[0]:-$0}) > /dev/null && pwd)
if [ -f "$REPCOURANT/../module.conf" ]; then
	source "$REPCOURANT/../module.conf"
else
	echo "module.conf introuvable !"
	exit 1
fi

# ------------------------------------------------------------------------------
# Test/gestion de la ligne de commande
# ------------------------------------------------------------------------------

if [ $# -ne 1 ]; then
	echo "Nettoyage de l'arborescence du module « $MODULENAME »"
	echo
	echo "usage : nettoyage <--all|ISTEX_SESSION>"
	echo "--all : nettoie *tous* les répertoires"
	echo "ISTEX_SESSION : nettoie seulement les répertoires de la session correspondante"
	exit 1
fi

if [ $1 == "--all" ]; then

	echo "Fonctionnalité désactivée, car susceptible de provoquer un \"rm /\" "

	# echo "Nettoyage global de toute l'arborescence de $MODULENAME"

	# # Nettoyage
	# echo "...nettoyage de « $DIR_IN »"
	# rm -Rf $DIR_IN/*
	# echo "...nettoyage de « $DIR_OUT »"
	# rm -Rf $DIR_OUT/*
	# echo "...nettoyage de « $DIR_ERR »"
	# rm -Rf $DIR_ERR/*
	# echo "...nettoyage de « $DIR_LOGS »"
	# rm -Rf $DIR_LOGS/*
	# echo "...nettoyage de « $DIR_SESSIONS »"
	# rm -Rf $DIR_SESSIONS/*
	# echo "...nettoyage de « $DIR_TMP »"
	# rm -Rf $DIR_TMP/*

	# Nettoyage du in en conservant l'arborescence

	# find $DIR_IN -type f | $PARALLEL rm
	# find $DIR_IN -type l | $PARALLEL rm

else

	echo "Session définie à « $ISTEX_SESSION »"
	ISTEX_SESSION="$1"

	echo "Nettoyage de la session $ISTEX_SESSION de $MODULENAME"

	# Nettoyage
	echo "...nettoyage de « $DIR_IN/$ISTEX_SESSION »"
	rm -Rf $DIR_IN/$ISTEX_SESSION/
	echo "...nettoyage de « $DIR_OUT/$ISTEX_SESSION »"
	rm -Rf $DIR_OUT/$ISTEX_SESSION
	echo "...nettoyage de « $DIR_ERR/$ISTEX_SESSION »"
	rm -Rf $DIR_ERR/$ISTEX_SESSION
	echo "...nettoyage de « $DIR_LOGS/$ISTEX_SESSION »"
	rm -Rf $DIR_LOGS/$ISTEX_SESSION
	echo "...nettoyage de « $DIR_SESSIONS/$ISTEX_SESSION »"
	rm -Rf $DIR_SESSIONS/$ISTEX_SESSION
	echo "...nettoyage de « $DIR_TMP/$ISTEX_SESSION »"
	rm -Rf $DIR_TMP/$ISTEX_SESSION

	# Nettoyage du in en conservant l'arborescence
	# find $DIR_IN/$ISTEX_SESSION/ -type f | $PARALLEL rm
	# find $DIR_IN/$ISTEX_SESSION/ -type l | $PARALLEL rm
fi


echo "Fin !"
exit 0

